name: linters

on:
    pull_request:
        branches:
            - 'main'

jobs:
    execute:
        name: check-format
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20.x]

        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'

            - run: npm ci
            - run: npm run check-format
              continue-on-error: true
